<a href="https://colab.research.google.com/github/AAnirudh07/HASOC-2021-Indo-Aryan/blob/main/Code/HASOC_Eng.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TASK1A: HASOC FIRE 2021 for English

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
import seaborn as sns
import pandas_profiling
sns.set() 
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline
import nltk  
# nltk.download()
from nltk.corpus import stopwords
from wordcloud import WordCloud
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
from nltk.stem import PorterStemmer
nltk.download('punkt')
from nltk.tokenize import word_tokenize 
import matplotlib.animation as animation
import operator
import plotly.express as px
from collections import Counter
from sklearn.feature_extraction.text import TfidfVectorizer as TFID

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [ ]:
import os
from google.colab import drive
drive.mount('/content/drive',force_remount=True)
os.chdir('/content/drive/My Drive/IoTScenarios')
print("Change successful.")

Mounted at /content/drive
Change successful.

In [ ]:
df = pd.read_csv(filepath_or_buffer='/content/drive/My Drive/HASOC-IndoAryan/Task1/en_Hasoc2021_train.csv');
df.describe()

        Unnamed: 0
count  3843.000000
mean   2558.799375
std    1477.088070
min       1.000000
25%    1276.500000
50%    2574.000000
75%    3828.000000
max    5121.000000

In [ ]:
df.head()

   Unnamed: 0                       _id  ... task_1 task_2
0        4986  60c5d6bf5659ea5e55defa2c  ...    HOF   PRFN
1        3394  60c5d6bf5659ea5e55def461  ...    HOF   OFFN
2        1310  60c5d6bf5659ea5e55defaad  ...    NOT   NONE
3        3390  60c5d6bf5659ea5e55def419  ...    HOF   OFFN
4        4626  60c5d6bf5659ea5e55def7fa  ...    HOF   OFFN

[5 rows x 5 columns]

In [ ]:
df.columns = ['no_name','id','original_text','task1','task2']

In [ ]:
df.head()

   no_name                        id  ... task1 task2
0     4986  60c5d6bf5659ea5e55defa2c  ...   HOF  PRFN
1     3394  60c5d6bf5659ea5e55def461  ...   HOF  OFFN
2     1310  60c5d6bf5659ea5e55defaad  ...   NOT  NONE
3     3390  60c5d6bf5659ea5e55def419  ...   HOF  OFFN
4     4626  60c5d6bf5659ea5e55def7fa  ...   HOF  OFFN

[5 rows x 5 columns]

In [ ]:
#Retain only the letters and spaces
df['clean_text'] = df['original_text'].apply(lambda x: re.sub(r'[^a-zA-Z ]+', '', x.lower()))
df.head()

   no_name  ...                                         clean_text
0     4986  ...  wealth if you made it through this ampamp were...
1     3394  ...  technically thats still turning back the clock...
2     1310  ...  vmbjp bjpbengal bjpindia narendramodi jpnadda ...
3     3390  ...   krtoprakyigit soldier of japan who has dick head
4     4626  ...  blueheartedly youd be better off asking who do...

[5 rows x 6 columns]

In [ ]:
import nltk
nltk.download('stopwords')
df['clean_text'] = df['clean_text'].apply(lambda x : ' '.join([word for word in x.split() if not word in set(stopwords.words('english'))]))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
df.head()

   no_name  ...                                         clean_text
0     4986  ...  wealth made ampamp able start making money sus...
1     3394  ...  technically thats still turning back clock dic...
2     1310  ...  vmbjp bjpbengal bjpindia narendramodi jpnadda ...
3     3390  ...              krtoprakyigit soldier japan dick head
4     4626  ...  blueheartedly youd better asking doesnt think ...

[5 rows x 6 columns]

In [ ]:
d = {'luv':'love','wud':'would','lyk':'like','wateva':'whatever','ttyl':'talk to you later','kul':'cool','fyn':'fine','omg':'oh my god','fam':'family','bruh':'brother',
    'cud':'could','fud':'food','govt':'government'}
df['clean_text'] = df['clean_text'].apply(lambda x : ' '.join(d[word] if word in d else word for word in x.split()))

In [ ]:
#tokenize the data
def tokenize(data):
  generated_token = list(data.split())
  return generated_token
df['tokenized_data'] = df['clean_text'].apply(lambda x: tokenize(x))
df.head()

   no_name  ...                                     tokenized_data
0     4986  ...  [wealth, made, ampamp, able, start, making, mo...
1     3394  ...  [technically, thats, still, turning, back, clo...
2     1310  ...  [vmbjp, bjpbengal, bjpindia, narendramodi, jpn...
3     3390  ...        [krtoprakyigit, soldier, japan, dick, head]
4     4626  ...  [blueheartedly, youd, better, asking, doesnt, ...

[5 rows x 7 columns]

In [ ]:
sum = 0
for i in df['tokenized_data']:
  sum += len(i)
sum/df.shape[0]

15.098360655737705

In [ ]:
#Now apply lemmatization to reduce the data to its base form
ps = nltk.PorterStemmer()
def stemming(list_of_words):
  stemmed_list = [ps.stem(word) for word in list_of_words]
  return stemmed_list
df['stemmed_words'] = df['tokenized_data'].apply(lambda x: stemming(x))
df.head()
# lemmatizer = WordNetLemmatizer()
# df['lemmatized_text'] = df['clean_text'].apply(lambda x : ' '.join([lemmatizer.lemmatize(word) for word in x.split()]))

   no_name  ...                                      stemmed_words
0     4986  ...  [wealth, made, ampamp, abl, start, make, money...
1     3394  ...  [technic, that, still, turn, back, clock, dick...
2     1310  ...  [vmbjp, bjpbengal, bjpindia, narendramodi, jpn...
3     3390  ...        [krtoprakyigit, soldier, japan, dick, head]
4     4626  ...  [blueheartedli, youd, better, ask, doesnt, thi...

[5 rows x 8 columns]

In [ ]:
df.head()

   no_name  ...                                      stemmed_words
0     4986  ...  [wealth, made, ampamp, abl, start, make, money...
1     3394  ...  [technic, that, still, turn, back, clock, dick...
2     1310  ...  [vmbjp, bjpbengal, bjpindia, narendramodi, jpn...
3     3390  ...        [krtoprakyigit, soldier, japan, dick, head]
4     4626  ...  [blueheartedli, youd, better, ask, doesnt, thi...

[5 rows x 8 columns]

In [ ]:
df['stemmed_sentences'] = df['stemmed_words'].apply(lambda x: ' '.join(x))

In [ ]:
from sklearn.model_selection import train_test_split
task1_labels = df['task1']
xtrain, xtest, ytrain, ytest = train_test_split(df['stemmed_sentences'],task1_labels,test_size =0.2,stratify=task1_labels,random_state=42)

In [ ]:
# df['stemmed_sentences'] = df['original_text']
#Now let's vectorize the data
tfidf_vectorizer = TFID(use_idf=True,max_features=5000)
train_vecs=tfidf_vectorizer.fit_transform(xtrain)

In [ ]:
import pickle
pickle.dump(tfidf_vectorizer,open('/content/drive/My Drive/feature.pkl',"wb"))

In [ ]:
def create_vectorized_df(tfidf_vectorizer_vectors):
  ret_arr = []
  for i in range(tfidf_vectorizer_vectors.shape[0]):
    check = tfidf_vectorizer_vectors[i].T.todense()
    arr_d = (np.asarray(check)).flatten()
    ret_arr.append(pd.DataFrame(arr_d,index=tfidf_vectorizer.get_feature_names()))
  return ret_arr

In [ ]:
train_vectorized_array = create_vectorized_df(train_vecs)
train_vectorized_df = pd.concat(train_vectorized_array,axis=1)
train_vectorized_df.columns = [i for i in range(train_vectorized_df.shape[1])]
traindf = pd.DataFrame(data=train_vectorized_df).T
traindf

      aajtak  aala  aap   ab  ...  zouyuetweet  zoyahighvib  zubymus  zzss
0        0.0   0.0  0.0  0.0  ...          0.0          0.0      0.0   0.0
1        0.0   0.0  0.0  0.0  ...          0.0          0.0      0.0   0.0
2        0.0   0.0  0.0  0.0  ...          0.0          0.0      0.0   0.0
3        0.0   0.0  0.0  0.0  ...          0.0          0.0      0.0   0.0
4        0.0   0.0  0.0  0.0  ...          0.0          0.0      0.0   0.0
...      ...   ...  ...  ...  ...          ...          ...      ...   ...
3069     0.0   0.0  0.0  0.0  ...          0.0          0.0      0.0   0.0
3070     0.0   0.0  0.0  0.0  ...          0.0          0.0      0.0   0.0
3071     0.0   0.0  0.0  0.0  ...          0.0          0.0      0.0   0.0
3072     0.0   0.0  0.0  0.0  ...          0.0          0.0      0.0   0.0
3073     0.0   0.0  0.0  0.0  ...          0.0          0.0      0.0   0.0

[3074 rows x 5000 columns]

In [ ]:
test_vecs=tfidf_vectorizer.transform(xtest)
test_vectorized_array = create_vectorized_df(test_vecs)
test_vectorized_df = pd.concat(test_vectorized_array,axis=1)
test_vectorized_df.columns = [i for i in range(test_vectorized_df.shape[1])]
testdf = pd.DataFrame(data=test_vectorized_df).T
testdf

     aajtak  aala  aap   ab  ...  zouyuetweet  zoyahighvib  zubymus  zzss
0       0.0   0.0  0.0  0.0  ...          0.0          0.0      0.0   0.0
1       0.0   0.0  0.0  0.0  ...          0.0          0.0      0.0   0.0
2       0.0   0.0  0.0  0.0  ...          0.0          0.0      0.0   0.0
3       0.0   0.0  0.0  0.0  ...          0.0          0.0      0.0   0.0
4       0.0   0.0  0.0  0.0  ...          0.0          0.0      0.0   0.0
..      ...   ...  ...  ...  ...          ...          ...      ...   ...
764     0.0   0.0  0.0  0.0  ...          0.0          0.0      0.0   0.0
765     0.0   0.0  0.0  0.0  ...          0.0          0.0      0.0   0.0
766     0.0   0.0  0.0  0.0  ...          0.0          0.0      0.0   0.0
767     0.0   0.0  0.0  0.0  ...          0.0          0.0      0.0   0.0
768     0.0   0.0  0.0  0.0  ...          0.0          0.0      0.0   0.0

[769 rows x 5000 columns]

In [ ]:
ttdf = pd.DataFrame(data=df['stemmed_sentences'])

In [ ]:
ttdf.head()

                                   stemmed_sentences
0  wealth made ampamp abl start make money sustai...
1  technic that still turn back clock dick head h...
2  vmbjp bjpbengal bjpindia narendramodi jpnadda ...
3              krtoprakyigit soldier japan dick head
4  blueheartedli youd better ask doesnt think he ...

Task 1 RNN

In [ ]:
import tensorflow as tf
# The maximum number of words to be used. (most frequent)
MAX_NB_WORDS = 35000
# Max number of words in each message.
MAX_SEQUENCE_LENGTH = 50
# This is fixed.
EMBEDDING_DIM = 110
tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words=MAX_NB_WORDS, filters='!"#$%&()*+,-./:;<=>?@[\]^_`{|}~', lower=True)
tokenizer.fit_on_texts(ttdf['stemmed_sentences'].values)
word_index = tokenizer.word_index
print('Found %s unique tokens.' % len(word_index))

Found 12144 unique tokens.

In [ ]:
X = tokenizer.texts_to_sequences(df['stemmed_sentences'].values)
X = tf.keras.preprocessing.sequence.pad_sequences(X, maxlen=MAX_SEQUENCE_LENGTH)
print('Shape of data tensor:', X.shape)

Shape of data tensor: (3843, 50)

In [ ]:
Y = pd.get_dummies(df['task1']).values

In [ ]:
from sklearn.model_selection import train_test_split
nxtrain, nxtest, nytrain, nytest = train_test_split(X,Y,test_size =0.1,stratify=Y,random_state=42)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout
from keras.layers import Embedding

In [ ]:
regressor = Sequential()

In [ ]:
regressor.add(Embedding(MAX_NB_WORDS, EMBEDDING_DIM, input_length=X.shape[1]))
regressor.add(Dropout(0.2))

In [ ]:
regressor.add(LSTM(units = 40))
regressor.add(Dropout(0.2))

In [ ]:
regressor.add(Dense(2, activation='softmax'))

In [ ]:
regressor.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
epochs = 10
batch_size = 64
history = regressor.fit(nxtrain, nytrain, epochs=epochs, batch_size=batch_size,validation_split=0.1,callbacks=[tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3, min_delta=0.0001)])

Epoch 1/10
49/49 [==============================] - 7s 101ms/step - loss: 0.6444 - accuracy: 0.6469 - val_loss: 0.6145 - val_accuracy: 0.6618
Epoch 2/10
49/49 [==============================] - 4s 87ms/step - loss: 0.5267 - accuracy: 0.7272 - val_loss: 0.5225 - val_accuracy: 0.7832
Epoch 3/10
49/49 [==============================] - 4s 86ms/step - loss: 0.3066 - accuracy: 0.8907 - val_loss: 0.5480 - val_accuracy: 0.7659
Epoch 4/10
49/49 [==============================] - 4s 84ms/step - loss: 0.1491 - accuracy: 0.9582 - val_loss: 0.6118 - val_accuracy: 0.7601
Epoch 5/10
49/49 [==============================] - 4s 83ms/step - loss: 0.0745 - accuracy: 0.9814 - val_loss: 0.7948 - val_accuracy: 0.7514

In [ ]:
accr = regressor.evaluate(nxtest,nytest)
accr[1]

13/13 [==============================] - 0s 10ms/step - loss: 0.8303 - accuracy: 0.7377

0.7376623153686523

Task 1 RF

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
ydf = pd.DataFrame(data=ytrain)
ytestdf = pd.DataFrame(data=ytest)
ydf['task1'] = le.fit_transform(ydf['task1'])
ytestdf['task1'] = le.fit_transform(ytestdf['task1'])

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfclf = RandomForestClassifier(n_jobs=2,random_state=0,verbose=True)
rfclf.fit(traindf,ydf)

[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  46 tasks      | elapsed:    6.4s
[Parallel(n_jobs=2)]: Done 100 out of 100 | elapsed:   13.9s finished

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=2,
                       oob_score=False, random_state=0, verbose=True,
                       warm_start=False)

In [ ]:
predic_res = rfclf.predict(testdf)
from sklearn.metrics import classification_report, confusion_matrix, f1_score, precision_score, recall_score, accuracy_score
print("----Accuracy-----  ")
print(accuracy_score( ytestdf , predic_res ))
print('----F1 score-----  ')
print(f1_score( ytestdf , predic_res ))
print('----Recall------- ')
print(recall_score(ytestdf , predic_res ))
print('----Precision----')
print(precision_score( ytestdf , predic_res))

[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  46 tasks      | elapsed:    0.1s
[Parallel(n_jobs=2)]: Done 100 out of 100 | elapsed:    0.1s finished

----Accuracy-----
0.8023407022106632
----F1 score-----
0.6897959183673469
----Recall-------
0.6282527881040892
----Precision----
0.7647058823529411

Task 1 Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0).fit(traindf,ydf)
predic_res = clf.predict(testdf)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, f1_score, precision_score, recall_score, accuracy_score
print("----Accuracy-----  ")
print(accuracy_score( ytestdf , predic_res ))
print('----F1 score-----  ')
print(f1_score( ytestdf , predic_res ))
print('----Recall------- ')
print(recall_score(ytestdf , predic_res ))
print('----Precision----')
print(precision_score( ytestdf , predic_res))

----Accuracy-----
0.7724317295188556
----F1 score-----
0.6013667425968109
----Recall-------
0.49070631970260226
----Precision----
0.7764705882352941

Task 1 SVM

In [ ]:
from sklearn import svm
SVM = svm.NuSVC(max_iter=100)
SVM=svm.NuSVC(nu=0.5,kernel='linear',degree=10,gamma='auto',probability=True)
SVM.fit(traindf, ydf)
print("Accuracy",SVM.score(testdf,ytestdf))

Accuracy 0.7737321196358907

Task 1 Test Set

In [ ]:
df = pd.read_csv(filepath_or_buffer='/content/drive/My Drive/HASOC-IndoAryan/Task1/test/en_Hasoc2021_test_task1.csv');
df.columns = ['id','original_text']
df['clean_text'] = df['original_text'].apply(lambda x: re.sub(r'[^a-zA-Z ]+', '', x.lower()))
nltk.download('stopwords')
df['clean_text'] = df['clean_text'].apply(lambda x : ' '.join([word for word in x.split() if not word in set(stopwords.words('english'))]))
d = {'luv':'love','wud':'would','lyk':'like','wateva':'whatever','ttyl':'talk to you later','kul':'cool','fyn':'fine','omg':'oh my god','fam':'family','bruh':'brother',
    'cud':'could','fud':'food','govt':'government'}
df['clean_text'] = df['clean_text'].apply(lambda x : ' '.join(d[word] if word in d else word for word in x.split()))
def tokenize(data):
  generated_token = list(data.split())
  return generated_token
df['tokenized_data'] = df['clean_text'].apply(lambda x: tokenize(x))
df.head()
ps = nltk.PorterStemmer()
def stemming(list_of_words):
  stemmed_list = [ps.stem(word) for word in list_of_words]
  return stemmed_list
df['stemmed_words'] = df['tokenized_data'].apply(lambda x: stemming(x))
df['stemmed_sentences'] = df['stemmed_words'].apply(lambda x: ' '.join(x))

#tfidf_vectorizer = pickle.load(open("'/content/drive/My Drive/feature.pkl'", 'rb'))
tfidf_vectorizer_vectors=tfidf_vectorizer.transform(df['stemmed_sentences'])


def create_vectorized_df(tfidf_vectorizer_vectors):
  ret_arr = []
  for i in range(tfidf_vectorizer_vectors.shape[0]):
    check = tfidf_vectorizer_vectors[i].T.todense()
    arr_d = (np.asarray(check)).flatten()
    ret_arr.append(pd.DataFrame(arr_d,index=tfidf_vectorizer.get_feature_names()))
  return ret_arr

vectorized_array = create_vectorized_df(tfidf_vectorizer_vectors)
vectorized_df = pd.concat(vectorized_array,axis=1)
vectorized_df.columns = [i for i in range(vectorized_df.shape[1])]
vdf = pd.DataFrame(data=vectorized_df).T
cols_remove = []
for col in vdf.columns:
    if len(vdf[col].unique()) <= 20: cols_remove.append(col)
vdf.drop(columns=cols_remove)
ttdf = pd.DataFrame(data=df['stemmed_sentences'])

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
ttdf.head()

                                   stemmed_sentences
0  fewer peopl come vaccin sad nurs covidvaccin vumc
1                  matthancock may true piss big dom
2                       laylaefc ive unfollow wanker
3  guy lose world jung label islamophobia httpstc...
4  thu death laugh sad merriment still covid indi...

In [ ]:
#Run the test set on the ML Models
#1. RF
test_predictions1 = rfclf.predict(vdf)
test_predictions1 = le.inverse_transform(test_predictions1)
test_predictions1 = list(test_predictions1)

[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  46 tasks      | elapsed:    0.1s
[Parallel(n_jobs=2)]: Done 100 out of 100 | elapsed:    0.2s finished

In [ ]:
#2. Logistic Regression
test_predictions2 = clf.predict(vdf)
test_predictions2 = le.inverse_transform(test_predictions2)
test_predictions2 = list(test_predictions2)

In [ ]:
#3. SVMNu
test_predictions3 = SVM.predict(vdf)
test_predictions3 = le.inverse_transform(test_predictions3)
test_predictions3 = list(test_predictions3)
test_predictions3

In [ ]:
ttdf.head()

                                   stemmed_sentences
0  fewer peopl come vaccin sad nurs covidvaccin vumc
1                  matthancock may true piss big dom
2                       laylaefc ive unfollow wanker
3  guy lose world jung label islamophobia httpstc...
4  thu death laugh sad merriment still covid indi...

In [ ]:
X = tokenizer.texts_to_sequences(df['stemmed_sentences'].values)
X = tf.keras.preprocessing.sequence.pad_sequences(X, maxlen=MAX_SEQUENCE_LENGTH)
print('Shape of data tensor:', X.shape)

Shape of data tensor: (1281, 50)

In [ ]:
class_names = ['HOF','NOT']

In [ ]:
test_predictions4 = regressor.predict(X)

In [ ]:
y_classes = test_predictions4.argmax(axis=-1)

In [ ]:
ans = []
for i in y_classes:
  if i==0 : ans.append('HOF')
  else: ans.append('NOT')
ans

In [ ]:
#now convert the results back to .csv file format
res1df = pd.DataFrame(data=df['id'])
res2df = pd.DataFrame(data=df['id'])
res3df = pd.DataFrame(data=df['id'])
res4df = pd.DataFrame(data=df['id'])
res1df['label'] = test_predictions1
res2df['label'] = test_predictions2
res3df['label'] = test_predictions3
res4df['label'] = ans

In [ ]:
res1df.head()

                         id label
0  60c5d6bf5659ea5e55deffcb   NOT
1  60c5d6bf5659ea5e55df028c   HOF
2  60c5d6bf5659ea5e55def377   HOF
3  60c5d6bf5659ea5e55def4c7   NOT
4  60c5d6bf5659ea5e55df01a6   NOT

In [ ]:
res2df.head()

                         id label
0  60c5d6bf5659ea5e55deffcb   NOT
1  60c5d6bf5659ea5e55df028c   HOF
2  60c5d6bf5659ea5e55def377   HOF
3  60c5d6bf5659ea5e55def4c7   NOT
4  60c5d6bf5659ea5e55df01a6   NOT

In [ ]:
res3df.head()

                         id label
0  60c5d6bf5659ea5e55deffcb   NOT
1  60c5d6bf5659ea5e55df028c   HOF
2  60c5d6bf5659ea5e55def377   HOF
3  60c5d6bf5659ea5e55def4c7   NOT
4  60c5d6bf5659ea5e55df01a6   NOT

In [ ]:
res4df.head()

                         id label
0  60c5d6bf5659ea5e55deffcb   NOT
1  60c5d6bf5659ea5e55df028c   HOF
2  60c5d6bf5659ea5e55def377   HOF
3  60c5d6bf5659ea5e55def4c7   HOF
4  60c5d6bf5659ea5e55df01a6   NOT

In [ ]:
res1df.to_csv('/content/drive/My Drive/eng_res1.csv',index=False)
res2df.to_csv('/content/drive/My Drive/eng_res2.csv',index=False)
res3df.to_csv('/content/drive/My Drive/eng_res3.csv',index=False)
res4df.to_csv('/content/drive/My Drive/eng_res4.csv',index=False)